// ============================================================
//  World Cup 2026 — My Predictions across 4 pools
//  Open index.html to view. Combined tab lines the same game
//  up across all four pools (code aliases handled in index.html).
// ============================================================
window.WORLDCUP_DATA = {
  meta: {
    title: "My World Cup 2026 Predictions",
    lastUpdated: "Jun 22, 2026"
  },

  pools: [
    {
      id: "lasmigas",
      name: "Las Migas",
      url: "https://www.lasmigas.pro/mi-zona/mis-pronosticos",
      predictions: [
        { matchKey: "MEX-RSA", stage: "Group A – Fecha 1", home: "México", away: "Sudáfrica", pick: "2-1" },
        { matchKey: "KOR-CZE", stage: "Group A – Fecha 1", home: "Corea del Sur", away: "República Checa", pick: "1-0" },
        { matchKey: "CAN-BIH", stage: "Group B – Fecha 1", home: "Canadá", away: "Bosnia y Herzegovina", pick: "2-1" },
        { matchKey: "QAT-SUI", stage: "Group B – Fecha 1", home: "Catar", away: "Suiza", pick: "0-2" },
        { matchKey: "USA-PAR", stage: "Group D – Fecha 1", home: "Estados Unidos", away: "Paraguay", pick: "1-2" },
        { matchKey: "AUS-TUR", stage: "Group D – Fecha 1", home: "Australia", away: "Turquía", pick: "1-2" },
        { matchKey: "BRA-MAR", stage: "Group C – Fecha 1", home: "Brasil", away: "Marruecos", pick: "3-1" },
        { matchKey: "HAI-SCO", stage: "Group C – Fecha 1", home: "Haití", away: "Escocia", pick: "0-3" },
        { matchKey: "GER-CUW", stage: "Group E – Fecha 1", home: "Alemania", away: "Curaçao", pick: "5-0" },
        { matchKey: "CIV-ECU", stage: "Group E – Fecha 1", home: "Costa de Marfil", away: "Ecuador", pick: "1-2" },
        { matchKey: "NED-JPN", stage: "Group F – Fecha 1", home: "Países Bajos", away: "Japón", pick: "2-1" },
        { matchKey: "SWE-TUN", stage: "Group F – Fecha 1", home: "Suecia", away: "Túnez", pick: "3-1" },
        { matchKey: "ESP-CPV", stage: "Group H – Fecha 1", home: "España", away: "Cabo Verde", pick: "6-1" },
        { matchKey: "KSA-URU", stage: "Group H – Fecha 1", home: "Arabia Saudita", away: "Uruguay", pick: "1-3" },
        { matchKey: "BEL-EGY", stage: "Group G – Fecha 1", home: "Bélgica", away: "Egipto", pick: "2-0" },
        { matchKey: "IRN-NZL", stage: "Group G – Fecha 1", home: "Irán", away: "Nueva Zelanda", pick: "1-1" },
        { matchKey: "FRA-SEN", stage: "Group I – Fecha 1", home: "Francia", away: "Senegal", pick: "3-1" },
        { matchKey: "IRQ-NOR", stage: "Group I – Fecha 1", home: "Iraq", away: "Noruega", pick: "0-2" },
        { matchKey: "ARG-ALG", stage: "Group J – Fecha 1", home: "Argentina", away: "Argelia", pick: "4-1" },
        { matchKey: "AUT-JOR", stage: "Group J – Fecha 1", home: "Austria", away: "Jordania", pick: "1-0" },
        { matchKey: "POR-COD", stage: "Group K – Fecha 1", home: "Portugal", away: "RD del Congo", pick: "5-1" },
        { matchKey: "UZB-COL", stage: "Group K – Fecha 1", home: "Uzbekistán", away: "Colombia", pick: "1-3" },
        { matchKey: "ENG-CRO", stage: "Group L – Fecha 1", home: "Inglaterra", away: "Croacia", pick: "3-1" },
        { matchKey: "GHA-PAN", stage: "Group L – Fecha 1", home: "Ghana", away: "Panamá", pick: "2-0" },
        { matchKey: "CZE-RSA", stage: "Group A – Fecha 2", home: "República Checa", away: "Sudáfrica", pick: "2-1" },
        { matchKey: "MEX-KOR", stage: "Group A – Fecha 2", home: "México", away: "Corea del Sur", pick: "2-1" },
        { matchKey: "SUI-BIH", stage: "Group B – Fecha 2", home: "Suiza", away: "Bosnia y Herzegovina", pick: "1-1" },
        { matchKey: "CAN-QAT", stage: "Group B – Fecha 2", home: "Canadá", away: "Catar", pick: "2-0" },
        { matchKey: "USA-AUS", stage: "Group D – Fecha 2", home: "Estados Unidos", away: "Australia", pick: "2-1" },
        { matchKey: "TUR-PAR", stage: "Group D – Fecha 2", home: "Turquía", away: "Paraguay", pick: "2-0" },
        { matchKey: "SCO-MAR", stage: "Group C – Fecha 2", home: "Escocia", away: "Marruecos", pick: "1-2" },
        { matchKey: "BRA-HAI", stage: "Group C – Fecha 2", home: "Brasil", away: "Haití", pick: "4-0" },
        { matchKey: "NED-SWE", stage: "Group F – Fecha 2", home: "Países Bajos", away: "Suecia", pick: "3-1" },
        { matchKey: "TUN-JPN", stage: "Group F – Fecha 2", home: "Túnez", away: "Japón", pick: "1-3" },
        { matchKey: "GER-CIV", stage: "Group E – Fecha 2", home: "Alemania", away: "Costa de Marfil", pick: "3-1" },
        { matchKey: "ECU-CUW", stage: "Group E – Fecha 2", home: "Ecuador", away: "Curaçao", pick: "4-0" },
        { matchKey: "ESP-KSA", stage: "Group H – Fecha 2", home: "España", away: "Arabia Saudita", pick: "4-1" },
        { matchKey: "URU-CPV", stage: "Group H – Fecha 2", home: "Uruguay", away: "Cabo Verde", pick: "3-0" },
        { matchKey: "BEL-IRN", stage: "Group G – Fecha 2", home: "Bélgica", away: "Irán", pick: "3-1" },
        { matchKey: "NZL-EGY", stage: "Group G – Fecha 2", home: "Nueva Zelanda", away: "Egipto", pick: "0-2" },
        { matchKey: "ARG-AUT", stage: "Group J – Fecha 2", home: "Argentina", away: "Austria", pick: "2-1" },
        { matchKey: "JOR-ALG", stage: "Group J – Fecha 2", home: "Jordania", away: "Argelia", pick: "1-1" },
        { matchKey: "FRA-IRQ", stage: "Group I – Fecha 2", home: "Francia", away: "Iraq", pick: "4-0" },
        { matchKey: "NOR-SEN", stage: "Group I – Fecha 2", home: "Noruega", away: "Senegal", pick: "2-0" },
        { matchKey: "POR-UZB", stage: "Group K – Fecha 2", home: "Portugal", away: "Uzbekistán", pick: "5-0" },
        { matchKey: "COL-COD", stage: "Group K – Fecha 2", home: "Colombia", away: "RD del Congo", pick: "4-0" },
        { matchKey: "ENG-GHA", stage: "Group L – Fecha 2", home: "Inglaterra", away: "Ghana", pick: "3-1" },
        { matchKey: "PAN-CRO", stage: "Group L – Fecha 2", home: "Panamá", away: "Croacia", pick: "1-2" },
        { matchKey: "SUI-CAN", stage: "Group B – Fecha 3", home: "Suiza", away: "Canadá", pick: "2-1" },
        { matchKey: "BIH-QAT", stage: "Group B – Fecha 3", home: "Bosnia y Herzegovina", away: "Catar", pick: "1-1" },
        { matchKey: "MAR-HAI", stage: "Group C – Fecha 3", home: "Marruecos", away: "Haití", pick: "3-1" },
        { matchKey: "SCO-BRA", stage: "Group C – Fecha 3", home: "Escocia", away: "Brasil", pick: "1-3" },
        { matchKey: "CZE-MEX", stage: "Group A – Fecha 3", home: "República Checa", away: "México", pick: "0-1" },
        { matchKey: "RSA-KOR", stage: "Group A – Fecha 3", home: "Sudáfrica", away: "Corea del Sur", pick: "1-2" },
        { matchKey: "ECU-GER", stage: "Group E – Fecha 3", home: "Ecuador", away: "Alemania", pick: "1-2" },
        { matchKey: "CUW-CIV", stage: "Group E – Fecha 3", home: "Curaçao", away: "Costa de Marfil", pick: "1-3" },
        { matchKey: "JPN-SWE", stage: "Group F – Fecha 3", home: "Japón", away: "Suecia", pick: "2-1" },
        { matchKey: "TUN-NED", stage: "Group F – Fecha 3", home: "Túnez", away: "Países Bajos", pick: "0-2" },
        { matchKey: "TUR-USA", stage: "Group D – Fecha 3", home: "Turquía", away: "Estados Unidos", pick: "2-1" },
        { matchKey: "PAR-AUS", stage: "Group D – Fecha 3", home: "Paraguay", away: "Australia", pick: "2-0" },
        { matchKey: "NOR-FRA", stage: "Group I – Fecha 3", home: "Noruega", away: "Francia", pick: "1-2" },
        { matchKey: "SEN-IRQ", stage: "Group I – Fecha 3", home: "Senegal", away: "Iraq", pick: "2-0" },
        { matchKey: "URU-ESP", stage: "Group H – Fecha 3", home: "Uruguay", away: "España", pick: "1-2" },
        { matchKey: "CPV-KSA", stage: "Group H – Fecha 3", home: "Cabo Verde", away: "Arabia Saudita", pick: "0-0" },
        { matchKey: "NZL-BEL", stage: "Group G – Fecha 3", home: "Nueva Zelanda", away: "Bélgica", pick: "0-3" },
        { matchKey: "EGY-IRN", stage: "Group G – Fecha 3", home: "Egipto", away: "Irán", pick: "1-1" },
        { matchKey: "PAN-ENG", stage: "Group L – Fecha 3", home: "Panamá", away: "Inglaterra", pick: "0-3" },
        { matchKey: "CRO-GHA", stage: "Group L – Fecha 3", home: "Croacia", away: "Ghana", pick: "2-1" },
        { matchKey: "COL-POR", stage: "Group K – Fecha 3", home: "Colombia", away: "Portugal", pick: "2-2" },
        { matchKey: "COD-UZB", stage: "Group K – Fecha 3", home: "RD del Congo", away: "Uzbekistán", pick: "0-0" },
        { matchKey: "JOR-ARG", stage: "Group J – Fecha 3", home: "Jordania", away: "Argentina", pick: "0-3" },
        { matchKey: "ALG-AUT", stage: "Group J – Fecha 3", home: "Argelia", away: "Austria", pick: "0-1" }
      ],
      specialAwards: [
        { award: "Grupo A – 1er Clasificado", pick: "México" },
        { award: "Grupo A – 2do Clasificado", pick: "Corea del Sur" },
        { award: "Grupo B – 1er Clasificado", pick: "Canadá" },
        { award: "Grupo B – 2do Clasificado", pick: "Suiza" },
        { award: "Grupo C – 1er Clasificado", pick: "Brasil" },
        { award: "Grupo C – 2do Clasificado", pick: "Marruecos" },
        { award: "Grupo D – 1er Clasificado", pick: "Turquía" },
        { award: "Grupo D – 2do Clasificado", pick: "Paraguay" },
        { award: "Grupo E – 1er Clasificado", pick: "Alemania" },
        { award: "Grupo E – 2do Clasificado", pick: "Ecuador" },
        { award: "Grupo F – 1er Clasificado", pick: "Países Bajos" },
        { award: "Grupo F – 2do Clasificado", pick: "Japón" },
        { award: "Grupo G – 1er Clasificado", pick: "Bélgica" },
        { award: "Grupo G – 2do Clasificado", pick: "Egipto" },
        { award: "Grupo H – 1er Clasificado", pick: "España" },
        { award: "Grupo H – 2do Clasificado", pick: "Uruguay" },
        { award: "Grupo I – 1er Clasificado", pick: "Francia" },
        { award: "Grupo I – 2do Clasificado", pick: "Noruega" },
        { award: "Grupo J – 1er Clasificado", pick: "Argentina" },
        { award: "Grupo J – 2do Clasificado", pick: "Argelia" },
        { award: "Grupo K – 1er Clasificado", pick: "Portugal" },
        { award: "Grupo K – 2do Clasificado", pick: "Colombia" },
        { award: "Grupo L – 1er Clasificado", pick: "Inglaterra" },
        { award: "Grupo L – 2do Clasificado", pick: "Croacia" },
        { award: "Mejor Tercero – Grupos ABCDF", pick: "Bosnia y Herzegovina" },
        { award: "Mejor Tercero – Grupos CDFGH", pick: "Escocia" },
        { award: "Mejor Tercero – Grupos CEFHI", pick: "Costa de Marfil" },
        { award: "Mejor Tercero – Grupos EHIJK", pick: "Senegal" },
        { award: "Mejor Tercero – Grupos BEFIJ", pick: "Austria" },
        { award: "Mejor Tercero – Grupos AEHIJ", pick: "República Checa" },
        { award: "Mejor Tercero – Grupos EFGIJ", pick: "Irán" },
        { award: "Mejor Tercero – Grupos DEIJL", pick: "Estados Unidos" },
        { award: "Champion", pick: "Brasil" },
        { award: "Third Place Winner", pick: "Francia" },
        { award: "Top Scorer", pick: "Harry Kane" },
        { award: "Best Group Stage Team", pick: "Argentina" },
        { award: "Worst Group Stage Team", pick: "Curaçao" }
      ]
    },

    {
      id: "haas",
      name: "FIFA Predictor (Haas)",
      url: "https://fifa-predictor-haas.vercel.app/matches",
      predictions: [
        { matchKey: "MEX-RSA", stage: "Group A", home: "Mexico", away: "South Africa", pick: "2-1" },
        { matchKey: "KOR-CZE", stage: "Group A", home: "Korea Republic", away: "Czechia", pick: "1-2" },
        { matchKey: "CAN-BIH", stage: "Group B", home: "Canada", away: "Bosnia & Herzegovina", pick: "2-1" },
        { matchKey: "USA-PAR", stage: "Group D", home: "USA", away: "Paraguay", pick: "1-2" },
        { matchKey: "QAT-SUI", stage: "Group B", home: "Qatar", away: "Switzerland", pick: "0-2" },
        { matchKey: "BRA-MAR", stage: "Group C", home: "Brazil", away: "Morocco", pick: "3-1" },
        { matchKey: "HAI-SCO", stage: "Group C", home: "Haiti", away: "Scotland", pick: "0-2" },
        { matchKey: "AUS-TUR", stage: "Group D", home: "Australia", away: "Türkiye", pick: "1-1" },
        { matchKey: "GER-CUW", stage: "Group E", home: "Germany", away: "Curaçao", pick: "6-0" },
        { matchKey: "NED-JPN", stage: "Group F", home: "Netherlands", away: "Japan", pick: "2-2" },
        { matchKey: "CIV-ECU", stage: "Group E", home: "Côte d'Ivoire", away: "Ecuador", pick: "1-1" },
        { matchKey: "SWE-TUN", stage: "Group F", home: "Sweden", away: "Tunisia", pick: "2-1" },
        { matchKey: "ESP-CPV", stage: "Group H", home: "Spain", away: "Cabo Verde", pick: "5-1" },
        { matchKey: "BEL-EGY", stage: "Group G", home: "Belgium", away: "Egypt", pick: "3-1" },
        { matchKey: "KSA-URU", stage: "Group H", home: "Saudi Arabia", away: "Uruguay", pick: "0-2" },
        { matchKey: "IRN-NZL", stage: "Group G", home: "IR Iran", away: "New Zealand", pick: "0-0" },
        { matchKey: "FRA-SEN", stage: "Group I", home: "France", away: "Senegal", pick: "3-0" },
        { matchKey: "IRQ-NOR", stage: "Group I", home: "Iraq", away: "Norway", pick: "1-3" },
        { matchKey: "ARG-ALG", stage: "Group J", home: "Argentina", away: "Algeria", pick: "1-0" },
        { matchKey: "AUT-JOR", stage: "Group J", home: "Austria", away: "Jordan", pick: "0-1" },
        { matchKey: "POR-COD", stage: "Group K", home: "Portugal", away: "Congo DR", pick: "2-0" },
        { matchKey: "ENG-CRO", stage: "Group L", home: "England", away: "Croatia", pick: "3-2" },
        { matchKey: "GHA-PAN", stage: "Group L", home: "Ghana", away: "Panama", pick: "2-2" },
        { matchKey: "UZB-COL", stage: "Group K", home: "Uzbekistan", away: "Colombia", pick: "0-3" },
        { matchKey: "CZE-RSA", stage: "Group A", home: "Czechia", away: "South Africa", pick: "2-2" },
        { matchKey: "SUI-BIH", stage: "Group B", home: "Switzerland", away: "Bosnia & Herzegovina", pick: "1-1" },
        { matchKey: "CAN-QAT", stage: "Group B", home: "Canada", away: "Qatar", pick: "3-1" },
        { matchKey: "MEX-KOR", stage: "Group A", home: "Mexico", away: "Korea Republic", pick: "2-0" },
        { matchKey: "USA-AUS", stage: "Group D", home: "USA", away: "Australia", pick: "2-0" },
        { matchKey: "SCO-MAR", stage: "Group C", home: "Scotland", away: "Morocco", pick: "1-1" },
        { matchKey: "BRA-HAI", stage: "Group C", home: "Brazil", away: "Haiti", pick: "5-0" },
        { matchKey: "TUR-PAR", stage: "Group D", home: "Türkiye", away: "Paraguay", pick: "1-0" },
        { matchKey: "NED-SWE", stage: "Group F", home: "Netherlands", away: "Sweden", pick: "2-1" },
        { matchKey: "GER-CIV", stage: "Group E", home: "Germany", away: "Côte d'Ivoire", pick: "2-1" },
        { matchKey: "ECU-CUW", stage: "Group E", home: "Ecuador", away: "Curaçao", pick: "2-0" },
        { matchKey: "TUN-JPN", stage: "Group F", home: "Tunisia", away: "Japan", pick: "0-2" },
        { matchKey: "ESP-KSA", stage: "Group H", home: "Spain", away: "Saudi Arabia", pick: "5-2" },
        { matchKey: "BEL-IRN", stage: "Group G", home: "Belgium", away: "IR Iran", pick: "3-1" },
        { matchKey: "URU-CPV", stage: "Group H", home: "Uruguay", away: "Cabo Verde", pick: "4-1" },
        { matchKey: "NZL-EGY", stage: "Group G", home: "New Zealand", away: "Egypt", pick: "1-1" },
        { matchKey: "ARG-AUT", stage: "Group J", home: "Argentina", away: "Austria", pick: "3-1" },
        { matchKey: "FRA-IRQ", stage: "Group I", home: "France", away: "Iraq", pick: "3-0" },
        { matchKey: "NOR-SEN", stage: "Group I", home: "Norway", away: "Senegal", pick: "2-1" },
        { matchKey: "JOR-ALG", stage: "Group J", home: "Jordan", away: "Algeria", pick: "0-0" },
        { matchKey: "POR-UZB", stage: "Group K", home: "Portugal", away: "Uzbekistan", pick: "4-1" },
        { matchKey: "ENG-GHA", stage: "Group L", home: "England", away: "Ghana", pick: "3-2" },
        { matchKey: "PAN-CRO", stage: "Group L", home: "Panama", away: "Croatia", pick: "1-2" },
        { matchKey: "COL-COD", stage: "Group K", home: "Colombia", away: "Congo DR", pick: "3-1" },
        { matchKey: "SUI-CAN", stage: "Group B", home: "Switzerland", away: "Canada", pick: "1-1" },
        { matchKey: "BIH-QAT", stage: "Group B", home: "Bosnia & Herzegovina", away: "Qatar", pick: "1-0" },
        { matchKey: "SCO-BRA", stage: "Group C", home: "Scotland", away: "Brazil", pick: "1-2" },
        { matchKey: "MAR-HAI", stage: "Group C", home: "Morocco", away: "Haiti", pick: "3-1" },
        { matchKey: "RSA-KOR", stage: "Group A", home: "South Africa", away: "Korea Republic", pick: "0-1" },
        { matchKey: "CZE-MEX", stage: "Group A", home: "Czechia", away: "Mexico", pick: "1-1" },
        { matchKey: "CUW-CIV", stage: "Group E", home: "Curaçao", away: "Côte d'Ivoire", pick: "0-2" },
        { matchKey: "ECU-GER", stage: "Group E", home: "Ecuador", away: "Germany", pick: "2-3" },
        { matchKey: "TUN-NED", stage: "Group F", home: "Tunisia", away: "Netherlands", pick: "1-2" },
        { matchKey: "JPN-SWE", stage: "Group F", home: "Japan", away: "Sweden", pick: "2-1" },
        { matchKey: "PAR-AUS", stage: "Group D", home: "Paraguay", away: "Australia", pick: "2-0" },
        { matchKey: "TUR-USA", stage: "Group D", home: "Türkiye", away: "USA", pick: "3-1" },
        { matchKey: "NOR-FRA", stage: "Group I", home: "Norway", away: "France", pick: "1-2" },
        { matchKey: "SEN-IRQ", stage: "Group I", home: "Senegal", away: "Iraq", pick: "2-2" },
        { matchKey: "URU-ESP", stage: "Group H", home: "Uruguay", away: "Spain", pick: "1-2" },
        { matchKey: "CPV-KSA", stage: "Group H", home: "Cabo Verde", away: "Saudi Arabia", pick: "1-2" },
        { matchKey: "NZL-BEL", stage: "Group G", home: "New Zealand", away: "Belgium", pick: "0-4" },
        { matchKey: "EGY-IRN", stage: "Group G", home: "Egypt", away: "IR Iran", pick: "1-1" },
        { matchKey: "PAN-ENG", stage: "Group L", home: "Panama", away: "England", pick: "1-2" },
        { matchKey: "CRO-GHA", stage: "Group L", home: "Croatia", away: "Ghana", pick: "1-2" },
        { matchKey: "COL-POR", stage: "Group K", home: "Colombia", away: "Portugal", pick: "3-3" },
        { matchKey: "COD-UZB", stage: "Group K", home: "Congo DR", away: "Uzbekistan", pick: "0-0" },
        { matchKey: "JOR-ARG", stage: "Group J", home: "Jordan", away: "Argentina", pick: "2-1" },
        { matchKey: "ALG-AUT", stage: "Group J", home: "Algeria", away: "Austria", pick: "0-0" }
      ],
      specialAwards: []
    },

    {
      id: "pollaya",
      name: "Pollaya (CEUP)",
      url: "https://game.pollaya.com/mis-grupos/90408/pronosticos",
      predictions: [
        { matchKey: "MEX-RSA", stage: "Grupo A", home: "México", away: "Sudáfrica", pick: "2-1" },
        { matchKey: "CRS-RCH", stage: "Grupo A", home: "Corea del Sur", away: "República Checa", pick: "1-0" },
        { matchKey: "RCH-RSA", stage: "Grupo A", home: "República Checa", away: "Sudáfrica", pick: "2-1" },
        { matchKey: "MEX-CRS", stage: "Grupo A", home: "México", away: "Corea del Sur", pick: "2-1" },
        { matchKey: "RSA-CRS", stage: "Grupo A", home: "Sudáfrica", away: "Corea del Sur", pick: "1-2" },
        { matchKey: "RCH-MEX", stage: "Grupo A", home: "República Checa", away: "México", pick: "0-1" },
        { matchKey: "CND-BIH", stage: "Grupo B", home: "Canadá", away: "Bosnia & Herzegovina", pick: "2-1" },
        { matchKey: "QAT-SUI", stage: "Grupo B", home: "Catar", away: "Suiza", pick: "0-2" },
        { matchKey: "SUI-BIH", stage: "Grupo B", home: "Suiza", away: "Bosnia & Herzegovina", pick: "1-1" },
        { matchKey: "CND-QAT", stage: "Grupo B", home: "Canadá", away: "Catar", pick: "2-0" },
        { matchKey: "SUI-CND", stage: "Grupo B", home: "Suiza", away: "Canadá", pick: "1-0" },
        { matchKey: "BIH-QAT", stage: "Grupo B", home: "Bosnia & Herzegovina", away: "Catar", pick: "1-0" },
        { matchKey: "BRA-MAR", stage: "Grupo C", home: "Brasil", away: "Marruecos", pick: "2-1" },
        { matchKey: "HAI-SCT", stage: "Grupo C", home: "Haití", away: "Escocia", pick: "0-3" },
        { matchKey: "SCT-MAR", stage: "Grupo C", home: "Escocia", away: "Marruecos", pick: "1-2" },
        { matchKey: "BRA-HAI", stage: "Grupo C", home: "Brasil", away: "Haití", pick: "4-0" },
        { matchKey: "MAR-HAI", stage: "Grupo C", home: "Marruecos", away: "Haití", pick: "2-1" },
        { matchKey: "SCT-BRA", stage: "Grupo C", home: "Escocia", away: "Brasil", pick: "1-3" },
        { matchKey: "USA-PRY", stage: "Grupo D", home: "Estados Unidos", away: "Paraguay", pick: "1-2" },
        { matchKey: "AUS-TKY", stage: "Grupo D", home: "Australia", away: "Turquía", pick: "1-2" },
        { matchKey: "USA-AUS", stage: "Grupo D", home: "Estados Unidos", away: "Australia", pick: "2-1" },
        { matchKey: "TKY-PRY", stage: "Grupo D", home: "Turquía", away: "Paraguay", pick: "2-0" },
        { matchKey: "TKY-USA", stage: "Grupo D", home: "Turquía", away: "Estados Unidos", pick: "2-1" },
        { matchKey: "PRY-AUS", stage: "Grupo D", home: "Paraguay", away: "Australia", pick: "2-0" },
        { matchKey: "ALE-CUW", stage: "Grupo E", home: "Alemania", away: "Curazao", pick: "6-0" },
        { matchKey: "CIV-ECU", stage: "Grupo E", home: "Costa de Marfil", away: "Ecuador", pick: "1-2" },
        { matchKey: "ALE-CIV", stage: "Grupo E", home: "Alemania", away: "Costa de Marfil", pick: "3-1" },
        { matchKey: "ECU-CUW", stage: "Grupo E", home: "Ecuador", away: "Curazao", pick: "3-0" },
        { matchKey: "CUW-CIV", stage: "Grupo E", home: "Curazao", away: "Costa de Marfil", pick: "1-3" },
        { matchKey: "ECU-ALE", stage: "Grupo E", home: "Ecuador", away: "Alemania", pick: "1-2" },
        { matchKey: "NED-JAP", stage: "Grupo F", home: "Paises Bajos", away: "Japón", pick: "2-1" },
        { matchKey: "SUE-TUN", stage: "Grupo F", home: "Suecia", away: "Túnez", pick: "3-1" },
        { matchKey: "NED-SUE", stage: "Grupo F", home: "Paises Bajos", away: "Suecia", pick: "3-1" },
        { matchKey: "TUN-JAP", stage: "Grupo F", home: "Túnez", away: "Japón", pick: "1-3" },
        { matchKey: "TUN-NED", stage: "Grupo F", home: "Túnez", away: "Paises Bajos", pick: "0-2" },
        { matchKey: "JAP-SUE", stage: "Grupo F", home: "Japón", away: "Suecia", pick: "1-2" },
        { matchKey: "BEL-EGI", stage: "Grupo G", home: "Bélgica", away: "Egipto", pick: "1-0" },
        { matchKey: "IRA-NZL", stage: "Grupo G", home: "Irán", away: "Nueva Zelanda", pick: "0-0" },
        { matchKey: "BEL-IRA", stage: "Grupo G", home: "Bélgica", away: "Irán", pick: "3-1" },
        { matchKey: "NZL-EGI", stage: "Grupo G", home: "Nueva Zelanda", away: "Egipto", pick: "0-2" },
        { matchKey: "NZL-BEL", stage: "Grupo G", home: "Nueva Zelanda", away: "Bélgica", pick: "0-3" },
        { matchKey: "EGI-IRA", stage: "Grupo G", home: "Egipto", away: "Irán", pick: "1-1" },
        { matchKey: "ESP-CPV", stage: "Grupo H", home: "España", away: "Cabo Verde", pick: "6-1" },
        { matchKey: "SAU-URU", stage: "Grupo H", home: "Arabia Saudita", away: "Uruguay", pick: "1-3" },
        { matchKey: "ESP-SAU", stage: "Grupo H", home: "España", away: "Arabia Saudita", pick: "4-1" },
        { matchKey: "URU-CPV", stage: "Grupo H", home: "Uruguay", away: "Cabo Verde", pick: "3-0" },
        { matchKey: "CPV-SAU", stage: "Grupo H", home: "Cabo Verde", away: "Arabia Saudita", pick: "0-0" },
        { matchKey: "URU-ESP", stage: "Grupo H", home: "Uruguay", away: "España", pick: "1-2" },
        { matchKey: "FRA-SEN", stage: "Grupo I", home: "Francia", away: "Senegal", pick: "3-1" },
        { matchKey: "IRK-NOR", stage: "Grupo I", home: "Irak", away: "Noruega", pick: "0-2" },
        { matchKey: "FRA-IRK", stage: "Grupo I", home: "Francia", away: "Irak", pick: "4-0" },
        { matchKey: "NOR-SEN", stage: "Grupo I", home: "Noruega", away: "Senegal", pick: "2-0" },
        { matchKey: "NOR-FRA", stage: "Grupo I", home: "Noruega", away: "Francia", pick: "2-2" },
        { matchKey: "SEN-IRK", stage: "Grupo I", home: "Senegal", away: "Irak", pick: "2-0" },
        { matchKey: "ARG-ALG", stage: "Grupo J", home: "Argentina", away: "Argelia", pick: "2-0" },
        { matchKey: "ATR-JOR", stage: "Grupo J", home: "Austria", away: "Jordania", pick: "1-1" },
        { matchKey: "ARG-ATR", stage: "Grupo J", home: "Argentina", away: "Austria", pick: "2-0" },
        { matchKey: "JOR-ALG", stage: "Grupo J", home: "Jordania", away: "Argelia", pick: "1-1" },
        { matchKey: "ALG-ATR", stage: "Grupo J", home: "Argelia", away: "Austria", pick: "0-1" },
        { matchKey: "JOR-ARG", stage: "Grupo J", home: "Jordania", away: "Argentina", pick: "0-3" },
        { matchKey: "POR-CON", stage: "Grupo K", home: "Portugal", away: "Congo", pick: "5-1" },
        { matchKey: "UZB-COL", stage: "Grupo K", home: "Uzbekistán", away: "Colombia", pick: "1-3" },
        { matchKey: "POR-UZB", stage: "Grupo K", home: "Portugal", away: "Uzbekistán", pick: "5-0" },
        { matchKey: "COL-CON", stage: "Grupo K", home: "Colombia", away: "Congo", pick: "4-0" },
        { matchKey: "COL-POR", stage: "Grupo K", home: "Colombia", away: "Portugal", pick: "2-2" },
        { matchKey: "CON-UZB", stage: "Grupo K", home: "Congo", away: "Uzbekistán", pick: "0-0" },
        { matchKey: "ING-CRO", stage: "Grupo L", home: "Inglaterra", away: "Croacia", pick: "3-1" },
        { matchKey: "GHN-PAN", stage: "Grupo L", home: "Ghana", away: "Panamá", pick: "2-0" },
        { matchKey: "ING-GHN", stage: "Grupo L", home: "Inglaterra", away: "Ghana", pick: "3-1" },
        { matchKey: "PAN-CRO", stage: "Grupo L", home: "Panamá", away: "Croacia", pick: "1-2" },
        { matchKey: "PAN-ING", stage: "Grupo L", home: "Panamá", away: "Inglaterra", pick: "0-3" },
        { matchKey: "CRO-GHN", stage: "Grupo L", home: "Croacia", away: "Ghana", pick: "2-1" }
      ],
      specialAwards: [
        { award: "1st Place (Champion)", pick: "España" },
        { award: "2nd Place (Runner-up)", pick: "Brasil" },
        { award: "3rd Place", pick: "Francia" },
        { award: "Goleador", pick: "Harry Kane" },
        { award: "Mejor jugador del torneo", pick: "Michael Olise" }
      ]
    },

    {
      id: "golpredictor",
      name: "Gol Predictor (UP Economía)",
      url: "https://www.golpredictor.com/pooldetail.aspx?pid=0,82e11018-c20b-4abe-9d45-b3ccb766e74a",
      predictions: [
        { matchKey: "MEX-RSA", stage: "Fecha 1", home: "México", away: "Sudáfrica", pick: "2-1" },
        { matchKey: "KOR-CZE", stage: "Fecha 1", home: "Corea del Sur", away: "República Checa", pick: "1-0" },
        { matchKey: "CAN-BIH", stage: "Fecha 1", home: "Canadá", away: "Bosnia-Herzegovina", pick: "0-0" },
        { matchKey: "USA-PAR", stage: "Fecha 1", home: "Estados Unidos", away: "Paraguay", pick: "1-1" },
        { matchKey: "QAT-SUI", stage: "Fecha 1", home: "Catar", away: "Suiza", pick: "0-2" },
        { matchKey: "BRA-MAR", stage: "Fecha 1", home: "Brasil", away: "Marruecos", pick: "2-0" },
        { matchKey: "HAI-SCO", stage: "Fecha 1", home: "Haití", away: "Escocia", pick: "0-1" },
        { matchKey: "AUS-TUR", stage: "Fecha 1", home: "Australia", away: "Turquía", pick: "1-2" },
        { matchKey: "GER-CUW", stage: "Fecha 1", home: "Alemania", away: "Curazao", pick: "6-0" },
        { matchKey: "NED-JPN", stage: "Fecha 1", home: "Países Bajos", away: "Japón", pick: "2-1" },
        { matchKey: "CIV-ECU", stage: "Fecha 1", home: "Costa de Marfil", away: "Ecuador", pick: "1-1" },
        { matchKey: "SWE-TUN", stage: "Fecha 1", home: "Suecia", away: "Túnez", pick: "2-2" },
        { matchKey: "ESP-CPV", stage: "Fecha 1", home: "España", away: "Cabo Verde", pick: "3-1" },
        { matchKey: "BEL-EGY", stage: "Fecha 1", home: "Bélgica", away: "Egipto", pick: "2-1" },
        { matchKey: "KSA-URU", stage: "Fecha 1", home: "Arabia Saudita", away: "Uruguay", pick: "1-2" },
        { matchKey: "IRN-NZL", stage: "Fecha 1", home: "Irán", away: "Nueva Zelanda", pick: "0-0" },
        { matchKey: "FRA-SEN", stage: "Fecha 1", home: "Francia", away: "Senegal", pick: "4-1" },
        { matchKey: "IRQ-NOR", stage: "Fecha 1", home: "Irak", away: "Noruega", pick: "1-3" },
        { matchKey: "ARG-ALG", stage: "Fecha 1", home: "Argentina", away: "Argelia", pick: "3-0" },
        { matchKey: "AUT-JOR", stage: "Fecha 1", home: "Austria", away: "Jordania", pick: "1-1" },
        { matchKey: "POR-COD", stage: "Fecha 1", home: "Portugal", away: "RD Congo", pick: "4-0" },
        { matchKey: "ENG-CRO", stage: "Fecha 1", home: "Inglaterra", away: "Croacia", pick: "2-1" },
        { matchKey: "GHA-PAN", stage: "Fecha 1", home: "Ghana", away: "Panamá", pick: "1-1" },
        { matchKey: "UZB-COL", stage: "Fecha 1", home: "Uzbekistán", away: "Colombia", pick: "0-3" },
        { matchKey: "CZE-RSA", stage: "Fecha 2", home: "República Checa", away: "Sudáfrica", pick: "1-1" },
        { matchKey: "SUI-BIH", stage: "Fecha 2", home: "Suiza", away: "Bosnia-Herzegovina", pick: "1-1" },
        { matchKey: "CAN-QAT", stage: "Fecha 2", home: "Canadá", away: "Catar", pick: "2-1" },
        { matchKey: "MEX-KOR", stage: "Fecha 2", home: "México", away: "Corea del Sur", pick: "2-0" },
        { matchKey: "USA-AUS", stage: "Fecha 2", home: "Estados Unidos", away: "Australia", pick: "2-1" },
        { matchKey: "SCO-MAR", stage: "Fecha 2", home: "Escocia", away: "Marruecos", pick: "1-3" },
        { matchKey: "BRA-HAI", stage: "Fecha 2", home: "Brasil", away: "Haití", pick: "3-0" },
        { matchKey: "TUR-PAR", stage: "Fecha 2", home: "Turquía", away: "Paraguay", pick: "1-1" },
        { matchKey: "NED-SWE", stage: "Fecha 2", home: "Países Bajos", away: "Suecia", pick: "2-1" },
        { matchKey: "GER-CIV", stage: "Fecha 2", home: "Alemania", away: "Costa de Marfil", pick: "2-1" },
        { matchKey: "ECU-CUW", stage: "Fecha 2", home: "Ecuador", away: "Curazao", pick: "4-1" },
        { matchKey: "TUN-JPN", stage: "Fecha 2", home: "Túnez", away: "Japón", pick: "1-2" },
        { matchKey: "ESP-KSA", stage: "Fecha 2", home: "España", away: "Arabia Saudita", pick: "5-1" },
        { matchKey: "BEL-IRN", stage: "Fecha 2", home: "Bélgica", away: "Irán", pick: "3-1" },
        { matchKey: "URU-CPV", stage: "Fecha 2", home: "Uruguay", away: "Cabo Verde", pick: "3-1" },
        { matchKey: "NZL-EGY", stage: "Fecha 2", home: "Nueva Zelanda", away: "Egipto", pick: "1-2" },
        { matchKey: "ARG-AUT", stage: "Fecha 2", home: "Argentina", away: "Austria", pick: "3-1" },
        { matchKey: "FRA-IRQ", stage: "Fecha 2", home: "Francia", away: "Irak", pick: "4-1" },
        { matchKey: "NOR-SEN", stage: "Fecha 2", home: "Noruega", away: "Senegal", pick: "2-1" },
        { matchKey: "JOR-ALG", stage: "Fecha 2", home: "Jordania", away: "Argelia", pick: "0-0" },
        { matchKey: "POR-UZB", stage: "Fecha 2", home: "Portugal", away: "Uzbekistán", pick: "3-0" },
        { matchKey: "ENG-GHA", stage: "Fecha 2", home: "Inglaterra", away: "Ghana", pick: "3-2" },
        { matchKey: "PAN-CRO", stage: "Fecha 2", home: "Panamá", away: "Croacia", pick: "1-2" },
        { matchKey: "COL-COD", stage: "Fecha 2", home: "Colombia", away: "RD Congo", pick: "3-1" },
        { matchKey: "SUI-CAN", stage: "Fecha 3", home: "Suiza", away: "Canadá", pick: "3-2" },
        { matchKey: "BIH-QAT", stage: "Fecha 3", home: "Bosnia-Herzegovina", away: "Catar", pick: "1-1" },
        { matchKey: "SCO-BRA", stage: "Fecha 3", home: "Escocia", away: "Brasil", pick: "1-3" },
        { matchKey: "MAR-HAI", stage: "Fecha 3", home: "Marruecos", away: "Haití", pick: "2-0" },
        { matchKey: "CZE-MEX", stage: "Fecha 3", home: "República Checa", away: "México", pick: "2-3" },
        { matchKey: "RSA-KOR", stage: "Fecha 3", home: "Sudáfrica", away: "Corea del Sur", pick: "1-2" },
        { matchKey: "CUW-CIV", stage: "Fecha 3", home: "Curazao", away: "Costa de Marfil", pick: "0-2" },
        { matchKey: "ECU-GER", stage: "Fecha 3", home: "Ecuador", away: "Alemania", pick: "2-2" },
        { matchKey: "JPN-SWE", stage: "Fecha 3", home: "Japón", away: "Suecia", pick: "1-2" },
        { matchKey: "TUN-NED", stage: "Fecha 3", home: "Túnez", away: "Países Bajos", pick: "0-1" },
        { matchKey: "TUR-USA", stage: "Fecha 3", home: "Turquía", away: "Estados Unidos", pick: "2-2" },
        { matchKey: "PAR-AUS", stage: "Fecha 3", home: "Paraguay", away: "Australia", pick: "2-1" },
        { matchKey: "NOR-FRA", stage: "Fecha 3", home: "Noruega", away: "Francia", pick: "2-3" },
        { matchKey: "SEN-IRQ", stage: "Fecha 3", home: "Senegal", away: "Irak", pick: "2-1" },
        { matchKey: "CPV-KSA", stage: "Fecha 3", home: "Cabo Verde", away: "Arabia Saudita", pick: "1-2" },
        { matchKey: "URU-ESP", stage: "Fecha 3", home: "Uruguay", away: "España", pick: "1-1" },
        { matchKey: "EGY-IRN", stage: "Fecha 3", home: "Egipto", away: "Irán", pick: "1-2" },
        { matchKey: "NZL-BEL", stage: "Fecha 3", home: "Nueva Zelanda", away: "Bélgica", pick: "0-3" },
        { matchKey: "PAN-ENG", stage: "Fecha 3", home: "Panamá", away: "Inglaterra", pick: "1-2" },
        { matchKey: "CRO-GHA", stage: "Fecha 3", home: "Croacia", away: "Ghana", pick: "0-0" },
        { matchKey: "COL-POR", stage: "Fecha 3", home: "Colombia", away: "Portugal", pick: "1-1" },
        { matchKey: "COD-UZB", stage: "Fecha 3", home: "RD Congo", away: "Uzbekistán", pick: "0-0" },
        { matchKey: "ALG-AUT", stage: "Fecha 3", home: "Argelia", away: "Austria", pick: "1-1" },
        { matchKey: "JOR-ARG", stage: "Fecha 3", home: "Jordania", away: "Argentina", pick: "1-5" }
      ],
      specialAwards: []
    }
  ]
};

// ============================================================
//  REAL RESULTS — fill in the final score as each game is played.
//  Key = canonical "HOME-AWAY" code (same as Las Migas). Leave "" until played.
//  A pool's pick turns green in the table when it matches exactly.
// ============================================================
window.WORLDCUP_RESULTS = {
  // ---- Matchday 1 ----
  "MEX-RSA": "2-0", "KOR-CZE": "2-1", "CAN-BIH": "1-1", "QAT-SUI": "1-1", "USA-PAR": "4-1", "AUS-TUR": "2-0",
  "BRA-MAR": "1-1", "HAI-SCO": "0-1", "GER-CUW": "7-1", "CIV-ECU": "1-0", "NED-JPN": "2-2", "SWE-TUN": "5-1",
  "ESP-CPV": "0-0", "KSA-URU": "1-1", "BEL-EGY": "1-1", "IRN-NZL": "2-2", "FRA-SEN": "3-1", "IRQ-NOR": "1-4",
  "ARG-ALG": "3-0", "AUT-JOR": "3-1", "POR-COD": "1-1", "UZB-COL": "1-3", "ENG-CRO": "4-2", "GHA-PAN": "1-0",
  // ---- Matchday 2 ----
  "CZE-RSA": "1-1", "MEX-KOR": "1-0", "SUI-BIH": "4-1", "CAN-QAT": "6-0", "USA-AUS": "2-0", "TUR-PAR": "0-1",
  "SCO-MAR": "0-1", "BRA-HAI": "3-0", "NED-SWE": "5-1", "TUN-JPN": "0-4", "GER-CIV": "2-1", "ECU-CUW": "0-0",
  "ESP-KSA": "4-0", "URU-CPV": "2-2", "BEL-IRN": "0-0", "NZL-EGY": "1-3", "ARG-AUT": "2-0", "JOR-ALG": "",
  "FRA-IRQ": "3-0", "NOR-SEN": "", "POR-UZB": "", "COL-COD": "", "ENG-GHA": "", "PAN-CRO": "",
  // ---- Matchday 3 ----
  "SUI-CAN": "", "BIH-QAT": "", "MAR-HAI": "", "SCO-BRA": "", "CZE-MEX": "", "RSA-KOR": "",
  "ECU-GER": "", "CUW-CIV": "", "JPN-SWE": "", "TUN-NED": "", "TUR-USA": "", "PAR-AUS": "",
  "NOR-FRA": "", "SEN-IRQ": "", "URU-ESP": "", "CPV-KSA": "", "NZL-BEL": "", "EGY-IRN": "",
  "PAN-ENG": "", "CRO-GHA": "", "COL-POR": "", "COD-UZB": "", "JOR-ARG": "", "ALG-AUT": ""
};
